import {
  FaBootstrap,
  FaCss3Alt,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaJs,
  FaNode,
  FaReact,
} from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";
import { IoLogoVercel } from "react-icons/io5";
import { RiTailwindCssFill } from "react-icons/ri";
import {
  SiExpress,
  SiMercadopago,
  SiNestjs,
  SiNextdotjs,
  SiPostgresql,
  SiRedux,
  SiTypeorm,
  SiTypescript,
} from "react-icons/si";
import { TbJson, TbMessageChatbot } from "react-icons/tb";

export const data = [
  {
    id: 1,
    img: "https://i.ibb.co/W3WvzFg/m4-copy.jpg",
    imgComplete: "https://i.ibb.co/FJjRR53/m4.jpg",
    title: "Web tipo Ecommerce digital",
    description: "Elaborada con NextTs, Express y Typeorm, 100% responsive",
    date: "10/06/24",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/PM4-COPY",
    urlDeploy:
      "https://vercel.live/link/pm-4-copy-git-main-agustinhaags-projects.vercel.app?via=deployment-domains-list&p=1",
    technology: [
      <SiTypescript className="text-blue-700"/>,
      <SiNextdotjs  className="text-black bg-white rounded-full"/>,
      <SiRedux className="text-violet-500"/>,
      <RiTailwindCssFill className="text-cyan-500"/>,
      <SiExpress className="bg-white rounded-full text-black p-0.5"/>,
      <FaCss3Alt className="text-cyan-600"/>,
      <FaNode className="text-black bg-lime-800 rounded-full p-0.5"/>,
      <SiPostgresql className="text-sky-700"/>,
      <FaGitAlt className="text-orange-700"/>,
      <FaGithub className="bg-black rounded-full"/>,
      <SiTypeorm className="text-red-700"/>,
      <IoLogoVercel className=" text-black"/>,
    ],
  },
  {
    id: 2,
    img: "https://i.ibb.co/mB4w9RH/pf.jpg",
    imgComplete: "https://i.ibb.co/5Gm7gbH/pf.jpg",
    title: "Web de gestión de servicios",
    description: "Elaborada con NextTs, Nest y Typeorm, 100% responsive",
    date: "16/08/24",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/PF-ServiceCar",
    urlDeploy:
      "https://vercel.live/link/pf-service-car-git-main-agustinhaags-projects.vercel.app?via=deployment-domains-list&p=1",
    technology: [
      <SiTypescript className="text-blue-700" />,
      <SiNextdotjs  className="text-black bg-white rounded-full" />,
      <SiNestjs className="text-rose-600"/>,
      <SiRedux className="text-violet-500" />,
      <RiTailwindCssFill className="text-cyan-500" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaNode className="text-black bg-lime-800 rounded-full p-0.5" />,
      <SiPostgresql className="text-sky-700" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FcGoogle />,
      <TbMessageChatbot />,
      <SiMercadopago className="text-cyan-500 bg-white rounded-full"/>,
      <SiTypeorm className="text-red-700" />,
      <IoLogoVercel className=" text-black" />,
    ],
  },
  {
    id: 3,
    img: "https://i.ibb.co/MnyVMGR/m3.jpg",
    imgComplete: "https://i.ibb.co/NZXgS4N/m3.jpg",
    title: "Web de gestión de turnos",
    description: "Elaborada con React, Express y Typeorm, 100% responsive",
    date: "25/04/24",
    status: "Finalizado",
    urlGithub: "https://github.com/pi-rym/PM3-Agustinhaag",
    technology: [
      <FaJs className="text-yellow-400"/>,
      <SiTypescript className="text-blue-700" />,
      <FaReact className="text-cyan-300"/>,
      <FaCss3Alt className="text-cyan-600" />,
      <FaNode className="text-black bg-lime-800 rounded-full p-0.5" />,
      <SiPostgresql className="text-sky-700" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <RiTailwindCssFill className="text-cyan-500" />,
      <SiTypeorm className="text-red-700" />,
      <SiExpress className="bg-white rounded-full text-black p-0.5" />,
    ],
  },

  {
    id: 4,
    img: "https://i.ibb.co/XL3NrJp/clima.jpg",
    title: "Web del servicio meteorológico",
    description: " Diseñada con ReactJs, Css y la api de Openweather",
    date: "21/10/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Clima_React-Version",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaReact className="text-cyan-300" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <TbJson className="text-violet-300"/>,
    ],
  },
  {
    id: 5,
    img: "https://i.ibb.co/5Bcwp8Z/Captura-de-pantalla-4-2-2024-142511-localhost.jpg",
    title: "Web de productos alimenticios",
    description:
      "Proyecto diseñado con React, Css/ Bootstrap, responsive y adaptable",
    date: "23/11/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Humaya",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaReact className="text-cyan-300" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700"/>,
      <SiExpress className="bg-white rounded-full text-black p-0.5" />,
      <FaNode className="text-black bg-lime-800 rounded-full p-0.5" />,
    ],
  },
  {
    id: 6,
    img: "https://i.ibb.co/chMty37/corporation.jpg",
    title: "Web tipo E-commerce",
    description: "Diseño web responsive y adaptable a cualquier dispositivo",
    date: "06/10/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Corporation",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaReact className="text-cyan-300" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
    ],
  },
  {
    id: 7,
    img: "https://i.ibb.co/6XGbMsk/tareas.jpg",
    title: "Web de tareas",
    description:
      "Proyecto diseñado con Javascript, Html y Css, responsive y adaptable",
    date: "12/05/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Tareas",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
      <FaHtml5 className="text-orange-600" />,
    ],
  },

  {
    id: 8,
    img: "https://i.ibb.co/LkFJt3y/funkpop.jpg",
    title: "E-commerce de Funko-pops",
    description: "Proyecto del programa codo a codo 4.0",
    date: "30/08/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Funkopop",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaReact className="text-cyan-300" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaHtml5 className="text-orange-600"/>,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
      <FaGitAlt className="text-orange-700" />,
      <FaNode className="text-black bg-lime-800 rounded-full p-0.5" />,
      <SiPostgresql className="text-sky-700" />,
      <SiExpress className="bg-white rounded-full text-black p-0.5" />,
    ],
  },
  {
    id: 9,
    img: "https://i.ibb.co/tYdbFWS/netflix.jpg",
    title: "Web tipo Netflix",
    description: "Elaborada con Html, Css y Javascript, 100% responsive",
    date: "05/04/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/P-gina-estilo-netflix",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaHtml5 className="text-orange-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
    ],
  },
  {
    id: 10,
    img: "https://i.ibb.co/p12n50L/3.jpg",
    title: "Encriptador de texto",
    description: "Proyecto del programa Aura Latam ONE",
    date: "23/05/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Encriptador",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaHtml5 className="text-orange-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
    ],
  },

  {
    id: 11,
    img: "https://i.ibb.co/3Rwz6K8/calc.jpg",
    title: "App calculadora",
    description: "100% funcional y responsive",
    date: "24/03/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Calculadora",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaHtml5 className="text-orange-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
    ],
  },
  {
    id: 12,
    img: "https://i.ibb.co/2YvrQdq/editor.jpg",
    title: "App para editar imagenes",
    description: "Elaborado con React, Css, 100% responsive",
    date: "09/10/23",
    status: "Finalizado",
    urlGithub:
      "https://github.com/Agustinhaag/CaC2023/tree/main/Editor/editor-app",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaReact className="text-cyan-300" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <FaBootstrap className="text-violet-700" />,
      <TbJson className="text-violet-300" />,
    ],
  },
  {
    id: 13,
    img: "https://i.ibb.co/Bjh4DH0/finanza.jpg",
    title: "App para gestionar finanzas",
    description: "Elaborado con React, Css, 100% responsive",
    date: "09/10/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/App_inversiones",
    technology: [
      <FaJs className="text-yellow-400" />,
      <FaReact className="text-cyan-300" />,
      <FaCss3Alt className="text-cyan-600" />,
      <FaGitAlt className="text-orange-700" />,
      <FaGithub className="bg-black rounded-full" />,
      <RiTailwindCssFill className="text-cyan-500" />,
    ],
  },
];
