import {
  FaBootstrap,
  FaCss3Alt,
  FaGitAlt,
  FaGithub,
  FaHtml5,
  FaJs,
  FaNode,
  FaReact,
} from "react-icons/fa";
import { FcGoogle } from "react-icons/fc";
import { IoLogoVercel } from "react-icons/io5";
import { RiTailwindCssFill } from "react-icons/ri";
import {
  SiExpress,
  SiMercadopago,
  SiNestjs,
  SiNextdotjs,
  SiPostgresql,
  SiRedux,
  SiTypeorm,
  SiTypescript,
} from "react-icons/si";
import { TbJson, TbMessageChatbot } from "react-icons/tb";

export const data = [
  {
    id: 1,
    img: "https://i.ibb.co/W3WvzFg/m4-copy.jpg",
    imgComplete: "https://i.ibb.co/FJjRR53/m4.jpg",
    title: "Web tipo Ecommerce digital",
    description: "Elaborada con NextTs, Express y Typeorm, 100% responsive",
    date: "10/06/24",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/PM4-COPY",
    urlDeploy:
      "https://vercel.live/link/pm-4-copy-git-main-agustinhaags-projects.vercel.app?via=deployment-domains-list&p=1",
    technology: [
      <SiTypescript />,
      <SiNextdotjs />,
      <SiRedux />,
      <RiTailwindCssFill />,
      <SiExpress />,
      <FaCss3Alt />,
      <FaNode />,
      <SiPostgresql />,
      <FaGitAlt />,
      <FaGithub />,
      <SiTypeorm />,
      <IoLogoVercel />,
    ],
  },
  {
    id: 2,
    img: "https://i.ibb.co/mB4w9RH/pf.jpg",
    imgComplete: "https://i.ibb.co/5Gm7gbH/pf.jpg",
    title: "Plataforma de gestión de servicios",
    description: "Elaborada con NextTs, Nest y Typeorm, 100% responsive",
    date: "16/08/24",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/PF-ServiceCar",
    urlDeploy:
      "https://vercel.live/link/pf-service-car-git-main-agustinhaags-projects.vercel.app?via=deployment-domains-list&p=1",
    technology: [
      <SiTypescript />,
      <SiNextdotjs />,
      <SiNestjs />,
      <SiRedux />,
      <RiTailwindCssFill />,
      <FaCss3Alt />,
      <FaNode />,
      <SiPostgresql />,
      <FaGitAlt />,
      <FaGithub />,
      <FcGoogle />,
      <TbMessageChatbot />,
      <SiMercadopago />,
      <SiTypeorm />,
      <IoLogoVercel />,
    ],
  },
  {
    id: 3,
    img: "https://i.ibb.co/MnyVMGR/m3.jpg",
    imgComplete: "https://i.ibb.co/NZXgS4N/m3.jpg",
    title: "Web de gestión de turnos",
    description: "Elaborada con React, Express y Typeorm, 100% responsive",
    date: "25/04/24",
    status: "Finalizado",
    urlGithub: "https://github.com/pi-rym/PM3-Agustinhaag",
    technology: [
      <FaJs />,
      <SiTypescript />,
      <FaReact />,
      <RiTailwindCssFill />,
      <FaCss3Alt />,
      <FaNode />,
      <SiPostgresql />,
      <FaGitAlt />,
      <FaGithub />,
      <SiTypeorm />,
      <SiExpress />,
    ],
  },

  {
    id: 4,
    img: "https://i.ibb.co/XL3NrJp/clima.jpg",
    title: "Web del servicio meteorológico",
    description: " Diseñada con ReactJs, Css y la api de Openweather",
    date: "21/10/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Clima_React-Version",
    technology: [
      <FaJs />,
      <FaReact />,
      <FaCss3Alt />,
      <FaGitAlt />,
      <FaGithub />,
      <TbJson />,
    ],
  },
  {
    id: 5,
    img: "https://i.ibb.co/5Bcwp8Z/Captura-de-pantalla-4-2-2024-142511-localhost.jpg",
    title: "Web de productos alimenticios",
    description:
      "Proyecto diseñado con React, Css/ Bootstrap, responsive y adaptable",
    date: "23/11/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Humaya",
    technology: [
      <FaJs />,
      <FaReact />,
      <FaCss3Alt />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
    ],
  },
  {
    id: 6,
    img: "https://i.ibb.co/chMty37/corporation.jpg",
    title: "Web tipo E-commerce",
    description: "Diseño web responsive y adaptable a cualquier dispositivo",
    date: "06/10/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Corporation",
    technology: [
      <FaJs />,
      <FaReact />,
      <FaCss3Alt />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
    ],
  },
  {
    id: 7,
    img: "https://i.ibb.co/6XGbMsk/tareas.jpg",
    title: "Web de tareas",
    description:
      "Proyecto diseñado con Javascript, Html y Css, responsive y adaptable",
    date: "12/05/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Tareas",
    technology: [
      <FaJs />,
      <FaCss3Alt />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
      <FaHtml5 />,
    ],
  },

  {
    id: 8,
    img: "https://i.ibb.co/LkFJt3y/funkpop.jpg",
    title: "E-commerce de Funko-pops",
    description: "Proyecto del programa codo a codo 4.0",
    date: "30/08/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Funkopop",
    technology: [
      <FaJs />,
      <FaReact />,
      <FaCss3Alt />,
      <FaHtml5 />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
      <FaNode />,
      <SiPostgresql />,
      <SiExpress />,
    ],
  },
  {
    id: 9,
    img: "https://i.ibb.co/tYdbFWS/netflix.jpg",
    title: "Web tipo Netflix",
    description: "Elaborada con Html, Css y Javascript, 100% responsive",
    date: "05/04/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/P-gina-estilo-netflix",
    technology: [
      <FaJs />,
      <FaCss3Alt />,
      <FaHtml5 />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
    ],
  },
  {
    id: 10,
    img: "https://i.ibb.co/p12n50L/3.jpg",
    title: "Encriptador de texto",
    description: "Proyecto del programa Aura Latam ONE",
    date: "23/05/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Encriptador",
    technology: [
      <FaJs />,
      <FaCss3Alt />,
      <FaHtml5 />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
    ],
  },

  {
    id: 11,
    img: "https://i.ibb.co/3Rwz6K8/calc.jpg",
    title: "App calculadora",
    description: "100% funcional y responsive",
    date: "24/03/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/Calculadora",
    technology: [
      <FaJs />,
      <FaCss3Alt />,
      <FaHtml5 />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
    ],
  },
  {
    id: 12,
    img: "https://i.ibb.co/2YvrQdq/editor.jpg",
    title: "App para editar imagenes",
    description: "Elaborado con React, Css, 100% responsive",
    date: "09/10/23",
    status: "Finalizado",
    urlGithub:
      "https://github.com/Agustinhaag/CaC2023/tree/main/Editor/editor-app",
    technology: [
      <FaJs />,
      <FaReact />,
      <FaCss3Alt />,
      <FaGitAlt />,
      <FaGithub />,
      <FaBootstrap />,
      <TbJson />,
    ],
  },
  {
    id: 13,
    img: "https://i.ibb.co/Bjh4DH0/finanza.jpg",
    title: "App para gestionar finanzas",
    description: "Elaborado con React, Css, 100% responsive",
    date: "09/10/23",
    status: "Finalizado",
    urlGithub: "https://github.com/Agustinhaag/App_inversiones",
    technology: [
      <FaJs />,
      <FaReact />,
      <FaCss3Alt />,
      <FaGitAlt />,
      <FaGithub />,
      <RiTailwindCssFill />,
    ],
  },
];
